### ISSUE TITLE
cannot find .exe for windows

### ISSUE THREAD

**Issue by vciulei** [hxim/paq8px#119]
Hi,

Readme says that for windows I should just download the .exe file and run it in the folder where my files are. However I cannot find any .exe, neither here nor in [kaitz's](https://github.com/kaitz/paq8pxd). Is there another way to install/ simple build on windows, perhaps with python? 

Thanks a lot!

**Comment by hxim** [comment]
I think you can find it here:
https://encode.su/threads/342-paq8px?p=61907&viewfull=1#post61907

**Comment by vciulei** [comment]
thank you!
