### ISSUE TITLE
Not issue but a request. ###How can I increase the compression speed?

### ISSUE THREAD

**Issue by AnsonHooL** [hxim/paq8px#135]
Hello~. It seems the paq8qx project performs so excellent in compression ratio. But I want to implement it into 
compress big data(.e.g., 1GB ) text compress. And the process speed is kB/s, which is too slow to practice in real.

Could  you so nicely to give me some advises in how to optimize the speed in text compress?

**Comment by L3P3** [comment]
The neural network is learning the minified stream I think, so your text is first converted into a minimal alphabet, I guess. There may be dictionary files so that you can precompress your text first. But I thought that paq is doing that already. Is it english text?

**Comment by AnsonHooL** [comment]
> The neural network is learning the minified stream I think, so your text is first converted into a minimal alphabet, I guess. There may be dictionary files so that you can precompress your text first. But I thought that paq is doing that already. Is it english text?

Thanks for your response. Yes. It is English text, exactly is text sampled in WIKI. And how could I optimize the process speed?

**Comment by L3P3** [comment]
I only know of the -1 flag which is the fastest compression mode. I think you could theoretically compress text first using multiple threads and then compress that result in paq. You may read this: http://mattmahoney.net/dc/text.html

**Comment by AnsonHooL** [comment]
> I only know of the -1 flag which is the fastest compression mode. I think you could theoretically compress text first using multiple threads and then compress that result in paq. You may read this: http://mattmahoney.net/dc/text.html
> But after the first stage (after removing the english text overhead), we will still have a file of over 200 megabytes of high-density data. I do not think paq could go over that in less than an hour.

Thanks a lot. One hour is too long. I want the compress speed up to at least 10MB/s. May be I should close some model (e.g., the model for picture) to accelerate the compress speed.

**Comment by L3P3** [comment]
It will always be a tradeoff between speed an compression ratio. I do not know what you want to do there but I think you would be fine by first compress using a english text model with a dictionary and then compress the result using xz, all using multiple threads in parallel.

**Comment by GotthardtZ** [comment]
>>I want the compress speed up to at least 10MB/s. 
>>It will always be a tradeoff between speed an compression ratio. 
Yes, it's a tradeoff. Paq8px is not targeting such a speed level - the opposite: it sacrifices it for better compression ratio. You'll need to visit other compressors which gives you the accepted speed level.
This issue may be closed.
