### ISSUE TITLE
cannot build in linux

### ISSUE THREAD

**Issue by Vyacheslav16669991111** [hxim/paq8px#167]
cmake ..
-- The C compiler identification is GNU 9.3.0
-- The CXX compiler identification is GNU 9.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found ZLIB: /usr/lib/x86_64-linux-gnu/libz.so (found version "1.2.11") 
CMake Error at CMakeLists.txt:40 (add_executable):
  Syntax error in cmake code at

    /home/slava/Загрузки/paq8px-master/CMakeLists.txt:40

  when parsing string

    model\BlockModel.cpp

  Invalid character escape '\B'.

CMake Error at CMakeLists.txt:40 (add_executable):
  Syntax error in cmake code at

    /home/slava/Загрузки/paq8px-master/CMakeLists.txt:40

  when parsing string

    model\ContextModelBlock.cpp

  Invalid character escape '\C'.

-- Configuring incomplete, errors occurred!
See also "/home/slava/Загрузки/paq8px-master/build/CMakeFiles/CMakeOutput.log".

**Comment by GotthardtZ** [comment]
Thank you for reporting this.
https://github.com/hxim/paq8px/pull/166 is going to fix it.

**Comment by GotthardtZ** [comment]
As #166  is merged, this issue may be closed.
