### ISSUE TITLE
Optimizing text compression

### ISSUE THREAD

**Issue by rafael2k** [hxim/paq8px#177]
Hi again,
In order to optimize compression of small texts (and may be some email headers with no random data or keys, just words, separators and ascii numbers) for English, Spanish and Portuguese, what would be the best approach? Can I insert some dictionaries to paq8px?

**Comment by L3P3** [comment]
As far as I know, there is a way to create a dictionary and reuse it. Or maybe I confuse this with other compressors that allow this. :thinking:

**Comment by L3P3** [comment]
Yes, look in the Readme at Notes on pre-training, note 2!

**Comment by rafael2k** [comment]
Read. Thanks!
: )
